name: Brett Dixon work n words
favicon: null
layout_spectrum: 0
typography_spectrum: 0.05643
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1E1517'
    - '#5D6478'
    - '#9AA3B4'
    - '#E0E0DF'
    - '#FC6D42'
  brandStrength: 0
  lightness: 0.5250896
  saturation: 0.3136201
  rhythmicContrast: 0.5125448
purpose: []
