name: Brett Dixon work n words
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  lightness: 0.4910394
  brandStrength: 0
  brandColors:
    - '#1E1517'
    - '#5D6478'
    - '#9AA3B4'
    - '#E0E0DF'
    - '#FC6D42'
  rhythmicContrast: 0.6810036
typography_spectrum: 0.02508961
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5430108
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
